name: DirtyArrows
main: nl.sugcube.dirtyarrows.DirtyArrows
version: '4.2'
api-version: 1.13
author: SugarCaney
website: 'https://twitter.com/CaneyDearie'
description: >
             Adds many new bow abilities, as well as a couple of archery related features.
commands:
  dirtyarrows:
    description: DirtyArrows
    permission: dirtyarrows
    aliases: da